### ISSUE TITLE
Ferm rules not persistent (surviving a reboot) ?

### ISSUE THREAD

**Issue by privacy-wolf** [MaxKellermann/ferm#18]
I'm not an expert for neither Linux nor iptables but wanted to get my iptables persistent via ferm. So I installed it on Debian via `sudo apt install ferm` and answered that it should be persistent (to to best of my knowledge at least). My ferm rules are stored in `/etc/ferm/ferm.conf` and work fine when applied manually (via `sudo apt ferm --interactive /etc/ferm/ferm.conf)`. The service was not running so I also started it manually via `sudo service ferm start` which also loads the ferm rules fine. However, with each reboot the ferm service is loaded but dead and no rules are applied. Did I do something wrong, did I miss or overlooked something else or is this how ferm is supposed to work?

**Comment by MaxKellermann** [comment]
Your bug report is not about ferm at all, but a help request about your operating system. It's not even a bug. My random guess is that you did not tell your operating system to start the `ferm` service automatically on boot, but I can only guess because your text lacks everything that would be needed to judge that. Anyway, off-topic.
