### ISSUE TITLE
Ferm allows the use of duplicate chain names

### ISSUE THREAD

**Issue by jhendryUK** [MaxKellermann/ferm#25]
This may or may not be a problem.

Some people may use this to dynamically add rules to chains. However this can be a problem if you re-use a chain name without realising, your firewall starts behaving in ways you do not expect.

I can patch this to make duplicate names be printed as a warning. Making it an error could break working configs.

Here is a test config and example output showing the situation.

[iptables.ferm.txt](https://github.com/MaxKellermann/ferm/files/1345856/iptables.ferm.txt)
[iptables.output.txt](https://github.com/MaxKellermann/ferm/files/1345857/iptables.output.txt)

**Comment by MaxKellermann** [comment]
This is actually as designed, because you can add rules to one chain in several places. For example, your includes can add more rules to a chain. But I understand your assumption that this can be error prone. Maybe a warning could be a good idea, because the original design may not be so good after all.
