### ISSUE TITLE
Two ipfilters in one rule leads to rendering error

### ISSUE THREAD

**Issue by endreszabo** [MaxKellermann/ferm#63]
Hi,

I've been using these statements for years but a recent upgrade has broken it:

```
@def $y7 = (44.128.0.0/16 fd4d:4045:e5e8::/48);
@def $snat_addr = (172.30.0.48 2a05:d018:563:7900::25);

table nat {
    chain POSTROUTING {
        saddr @ipfilter($y7) outerface eth0 SNAT to-source @ipfilter($snat_addr);
    }
}
```

And the generated result is (see the end of the line):
```
-A POSTROUTING --source 44.128.0.0/16 --out-interface eth0 --jump SNAT --to-source deferred=ARRAY(0x558f46950100)
```

```
# ferm /etc/ferm.conf 
iptables-restore v1.8.4 (legacy): Bad IP address "deferred=ARRAY(0x55d9d68ed478)"
# ferm --version
ferm 2.5.1
```

Thank you and keep up the good work!

**Comment by MaxKellermann** [comment]
Bisect found 2818accbdb6f28bfc56434ad4ff50b72fe71f5bb to be the first bad commit (@paravoid)

**Comment by paravoid** [comment]
Thanks for the report! 31bb5d3 should be the first bad commit, but this caused by all the work in fe99bc2. I pushed a PR in #64 that should do the trick. It also adds a variant of your config as an test in our test suite, so hopefully we'll avoid breaking that code path in the future.

Let us know if you find more errors like this. Hope this helps!

**Comment by endreszabo** [comment]
Thanks guys for the awesome fast response. I will give a try soon.
